### ISSUE TITLE
Version 1.0.0 Roadmap

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/halite#12]
Version 1.0.0 Roadmap:

### Mainline Features

- [x] Key encapsulation
   - [x] `Key`
   - [x] `Asymmetric\SecretKey`
   - [x] `Asymmetric\PublicKey`
   - [x] `KeyPair`
   - [x] `Symmetric\SecretKey`
- [x] String encryption/decryption
    - [x] Symmetric-key
    - [x] Asymmetric-key
- [x] Cookie encryption/decryption
- [x] Message signing
    - [x] Symmetric-key (HMAC)
    - [x] Digital signatures (EdDSA)
- [x] File encryption/decryption
    - [x] Symmetric-key
    - [x] Asymmetric-key
    - [x] Streaming checksum calculation
- [x] File authentication #13
    - [x] Asymmetric-key authentication (digital signature)
- [x] Password management
    - [x] Secure storage (hash-then-encrypt)
    - [x] Secure verification (verify MAC, decrypt, verify password)

### To Do Before Tagging 1.0.0

- [x] Fix that strange PHP 7 error.
- [x] Complete Documentation

### Possibly Before 1.0.0

- [ ] Launch an Interactive Downloadable Tutorial (separate project?)
- [ ] External audit
- [ ] Demo/Example Code

### Release Schedule

- [x] Version 0.6.0 (2015-10-24)
    - [x] First beta release
    - [x] Code freeze (outside of creating unit tests)
- [x] Version 0.N.0 (for N > 6) ...
    - [x] Amend anything that is broken until it ceases to break...
- [x] Version 1.0.0 (2015-11-06)
    - [x] Remove support for v0.x
