### ISSUE TITLE
Brainstorm for Halite 3.0.0

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/halite#37]
### TODO

- [x] Use a `HiddenString` container instead of exposing passwords to stack traces
- [x] Use [paragonie/constant_time_encoding](https://github.com/paragonie/constant_time_encoding); default to Base64UrlSafe
- [x] Use `final` where `abstract` is used now
- [x] Drop support for scrypt, simplify the KeyFactory and Password APIs

**Comment by frederikbosch** [comment]
[ ] Use `final` where `abstract` is used now.

**Comment by paragonie-scott** [comment]
Okay, I'm going to begin on v3.0.0 in the master branch.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/compare/v2.1.2...master

> 809 additions and 918 deletions. 

 So far we're at a net change of `-109` lines of code.
